### ISSUE TITLE
Cannot query index, ensure service and credential settings are correct.

### ISSUE THREAD

**Issue by brdwilkinson** [SDKits/ExamineX#32] opened 2021-05-25 06:25 UTC
We recently purchased ExamineX license and are having issues connecting to Azure Search Service. 

**Settings:**
- Umbraco Version: 8.11.1
- ExamineX: 1.2.0
- Examine: 1.0.5
- Azure Search Service on basic plan (This was installed when creating a new 'Azure Cognitive Search' service)
- ExamineX.SiteFriendlyName not set to the Web App Service name as we are testing on an App Service with a different name.

**Results:**
- No Search Results Found
- 500 Error on attempting to access Examine Management in Back Office (Error below)
- Search Service has no activity logged
- Indexing Errors in Logs (Error below)

**500 Error on attempting to access Examine Management in Back Office**
`An error occurred
The 'ObjectContent 1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.
Exception Details
System.InvalidOperationException: The 'ObjectContent 1' type failed to serialize the response body for content type 'application/json; charset=utf-8'.
Stacktrace
Inner Exception
System.Xml.XmlException: Root element is missing.
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at ExamineX.Shared.LicenseManager.a.A()
   at System.Lazy 1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy 1.get_Value()
   at ExamineX.Shared.LicenseManager.a()
   at System.Lazy 1.CreateValue()
   at System.Lazy 1.LazyInitValue()
   at System.Lazy 1.get_Value()
   at ExamineX.Shared.LicenseManager.IsValid()
   at ExamineX.AzureSearch.Umbraco.UmbracoAzureSearchIndex.IsHealthy()
   at Umbraco.Web.Editors.ExamineManagementController.CreateModel(IIndex index) in D:\a\1\s\src\Umbraco.Web\Editors\ExamineManagementController.cs:line 184
   at System.Linq.Enumerable.WhereSelectEnumerableIterator 2.MoveNext()
   at System.Linq.Buffer 1..ctor(IEnumerable 1 source)
   at System.Linq.OrderedEnumerable 1.<GetEnumerator>d__1.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.WebApi.AngularJsonMediaTypeFormatter.<WriteToStreamAsync>d__1.MoveNext() in D:\a\1\s\src\Umbraco.Web\WebApi\AngularJsonMediaTypeFormatter.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__22.MoveNext()`

**Log Error**
`Cannot query index, ensure service and credential settings are correct.
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at ExamineX.Shared.LicenseManager.a.A()
   at System.Lazy'1.CreateValue()
   at System.Lazy'1.LazyInitValue()
   at System.Lazy'1.get_Value()
   at ExamineX.Shared.LicenseManager.A()
   at System.Lazy'1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy'1.get_Value()
   at ExamineX.Shared.LicenseManager.get_Sku()
   at ExamineX.Shared.LicenseManagerExtensions.IsStandard(ILicenseManager licenseManager)
   at A.B.A(ExamineXConfig , String , ILicenseManager )
   at ExamineX.AzureSearch.AzureSearchIndex.get_AzureSearchIndexName()
   at ExamineX.AzureSearch.AzureSearchIndex.A(Lis'1& )
   at ExamineX.AzureSearch.AzureSearchIndex.D()
   at ExamineX.AzureSearch.AzureSearchIndex.a(Boolean )
   at ExamineX.AzureSearch.AzureSearchIndex.CreateIndex()
   at ExamineX.AzureSearch.Umbraco.UmbracoAzureSearchIndex.CreateIndex()
   at Umbraco.Examine.IndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 58
   at Umbraco.Web.Search.BackgroundIndexRebuilder.RebuildOnStartupTask.RebuildIndexes() in D:\a\1\s\src\Umbraco.Web\Search\BackgroundIndexRebuilder.cs:line 119
   at Umbraco.Web.Search.BackgroundIndexRebuilder.RebuildOnStartupTask.Run() in D:\a\1\s\src\Umbraco.Web\Search\BackgroundIndexRebuilder.cs:line 93`

**Comment by Shazwazza** [comment] 2021-05-25 16:26
Hi @brdwilkinson thanks for reporting and including the stack trace info.

This error will be caused by having a license file that is an invalid format and cannot be read. I will create a separate issue for that scenario and get a new patch release out.

Feel free to send over the license file that you have to support@sdkits.com so I can verify it.

On another note, when you say

> ExamineX.SiteFriendlyName not set to the Web App Service name as we are testing on an App Service with a different name.

the `ExamineX.SiteFriendlyName` is specifically tied to the license, the names must match with what is registered in the license to what is in config else the license validation will not succeed and it will display unlicensed in the back office.

**Comment by Shazwazza** [comment] 2021-05-26 20:54
The cause is due to this https://github.com/SDKits/ExamineX/issues/35

The fix is in v1.2.1

**Closed by Shazwazza** 2021-05-26 20:54 UTC
Labels: question
