### ISSUE TITLE
Trashed nodes remain in the DeliveryApiContentIndex index (ElasticSearch)

### ISSUE THREAD

**Issue by mcl-sz** [SDKits/ExamineX#106] opened 2024-06-10 14:40 UTC
**Describe the bug**
When a node is trashed, it remains in the DeliveryApiContentIndex.

**License ID**
Your ExamineX license Id (found in your license file) if you are running a licensed version.

**To Reproduce**
Install for example "Clean"-startkit from Paul Seal (https://marketplace.umbraco.com/package/clean).
Rebuild the indexes.
Delete the "About" node to the recyclebin.
Search for "About" in the DeliveryApiContentIndex index.

**Expected behavior**
The "About"-node should be deleted from the DeliveryApiContentIndex.

**Versions**

- ExamineX version 3.0.3
- Umbraco version: 13.3.2
- Examine version: 3.2.0

**Comment by Shazwazza** [comment] 2024-06-10 16:30
Duplicate of #105

**Comment by Shazwazza** [comment] 2024-06-10 18:26
Reopened - @mcl-sz This looks to be an Umbraco issue. If you disable the DeliveryApiContentIndex for ExamineX and then just rely on the Lucene based index, you'll see that the items that are trashed also still remain in the Lucene index.

**Comment by mcl-sz** [comment] 2024-06-10 18:59
@Shazwazza  i can't reproduce in Lucene. If i trash a node it's removed from de DeliveryApiContentIndex in Lucene.

Before delete:
![afbeelding](https://github.com/SDKits/ExamineX/assets/18614643/230206d0-e5ed-4fa4-b8df-81837b35aaa5)

After delete:
![afbeelding](https://github.com/SDKits/ExamineX/assets/18614643/7b73d3d2-21eb-4df6-9a6b-ab4c55abe57b)

**Comment by Shazwazza** [comment] 2024-06-10 20:22
Ah, must have been a bug in an earlier umbraco 13.x version that I was using. I upgraded to your version and it works with the Lucene index. It was due to this change https://github.com/umbraco/Umbraco-CMS/pull/15848

Which I will need to port to ExamineX too. I'll get another version published shortly.

**Closed** 2024-06-13 16:11 UTC
Labels: bug

**Comment by Shazwazza** [comment] 2024-06-13 16:12
@mcl-sz Fixed in https://github.com/SDKits/ExamineX/releases/tag/elastic-v3.0.5
